name: golive_cms_dev

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: golive_cms
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d golive_cms"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_SOURCE: postgresql://root:secret@postgres:5432/golive_cms?sslmode=disable
      DB_DRIVER: postgres
      SERVER_ADDRESS: "0.0.0.0:8080"
      API_PORT: ":8080"
      TOKEN_SYMMETRIC_KEY: "12345678901234567890123456789012"
      ACCESS_TOKEN_DURATION: "15m"
      REFRESH_TOKEN_DURATION: "24h"
    volumes:
      - .:/app
      - /app/tmp
      - go_modules:/go/pkg/mod
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start-dev.sh"]

volumes:
  postgres_data:
  go_modules:
