// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: post.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const createPosts = `-- name: CreatePosts :one
INSERT INTO posts (
    name,
    description,
    user_id,
    username,
    content,
    url,
    images
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, name, description, user_id, username, content, images, url, created_at, changed_at
`

type CreatePostsParams struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	UserID      int64    `json:"user_id"`
	Username    string   `json:"username"`
	Content     string   `json:"content"`
	Url         string   `json:"url"`
	Images      []string `json:"images"`
}

func (q *Queries) CreatePosts(ctx context.Context, arg CreatePostsParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPosts,
		arg.Name,
		arg.Description,
		arg.UserID,
		arg.Username,
		arg.Content,
		arg.Url,
		pq.Array(arg.Images),
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.Username,
		&i.Content,
		pq.Array(&i.Images),
		&i.Url,
		&i.CreatedAt,
		&i.ChangedAt,
	)
	return i, err
}
