// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	BlockSession(ctx context.Context, id uuid.UUID) error
	CountTotalMedia(ctx context.Context) (int64, error)
	CountTotalPosts(ctx context.Context) (int64, error)
	CountTotalSessions(ctx context.Context) (int64, error)
	CountTotalTaxonomies(ctx context.Context) (int64, error)
	CountTotalUsers(ctx context.Context) (int64, error)
	CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error)
	CreatePostMedia(ctx context.Context, arg CreatePostMediaParams) (PostMedium, error)
	CreatePostTaxonomy(ctx context.Context, arg CreatePostTaxonomyParams) (PostsTaxonomy, error)
	CreatePosts(ctx context.Context, arg CreatePostsParams) (Post, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTaxonomy(ctx context.Context, arg CreateTaxonomyParams) (Taxonomy, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserPost(ctx context.Context, arg CreateUserPostParams) (UserPost, error)
	DeleteMedia(ctx context.Context, id int64) error
	DeleteMediaByUserID(ctx context.Context, userID int64) error
	DeleteMediaPosts(ctx context.Context, mediaID int64) error
	DeletePost(ctx context.Context, id int64) error
	DeletePostMedia(ctx context.Context, arg DeletePostMediaParams) error
	DeletePostMedias(ctx context.Context, postID int64) error
	DeletePostTaxonomies(ctx context.Context, postID int64) error
	DeletePostTaxonomy(ctx context.Context, arg DeletePostTaxonomyParams) error
	DeletePostsByUserID(ctx context.Context, userID int64) error
	DeleteTaxonomy(ctx context.Context, id int64) error
	DeleteTaxonomyPosts(ctx context.Context, taxonomyID int64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserPost(ctx context.Context, postID int64) error
	DeleteUserPostsByUserID(ctx context.Context, userID int64) error
	DeleteUserSessions(ctx context.Context, id int64) error
	GetMedia(ctx context.Context, id int64) (Medium, error)
	GetMediaByPost(ctx context.Context, postID int64) ([]Medium, error)
	GetMediaByUser(ctx context.Context, arg GetMediaByUserParams) ([]Medium, error)
	GetMediaPostCount(ctx context.Context, mediaID int64) (int64, error)
	GetPopularMedia(ctx context.Context, limit int32) ([]GetPopularMediaRow, error)
	GetPopularTaxonomies(ctx context.Context, limit int32) ([]GetPopularTaxonomiesRow, error)
	GetPost(ctx context.Context, id int64) (Post, error)
	GetPostMediaCount(ctx context.Context, postID int64) (int64, error)
	GetPostTaxonomies(ctx context.Context, postID int64) ([]Taxonomy, error)
	GetPostTaxonomyCount(ctx context.Context, postID int64) (int64, error)
	GetPostWithMedia(ctx context.Context, id int64) (GetPostWithMediaRow, error)
	GetPostsByUserWithMedia(ctx context.Context, arg GetPostsByUserWithMediaParams) ([]GetPostsByUserWithMediaRow, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTaxonomy(ctx context.Context, id int64) (Taxonomy, error)
	GetTaxonomyByName(ctx context.Context, name string) (Taxonomy, error)
	GetTaxonomyPostCount(ctx context.Context, taxonomyID int64) (int64, error)
	GetTaxonomyPosts(ctx context.Context, arg GetTaxonomyPostsParams) ([]Post, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserMediaCount(ctx context.Context, userID int64) (int64, error)
	ListMedia(ctx context.Context, arg ListMediaParams) ([]Medium, error)
	ListMediaWithPostCount(ctx context.Context, arg ListMediaWithPostCountParams) ([]ListMediaWithPostCountRow, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error)
	ListPostsWithMedia(ctx context.Context, arg ListPostsWithMediaParams) ([]ListPostsWithMediaRow, error)
	ListSessionsByUser(ctx context.Context, userID int64) ([]Session, error)
	ListSessionsByUsername(ctx context.Context, username string) ([]Session, error)
	ListTaxonomies(ctx context.Context, arg ListTaxonomiesParams) ([]Taxonomy, error)
	ListTaxonomiesWithPostCount(ctx context.Context, arg ListTaxonomiesWithPostCountParams) ([]ListTaxonomiesWithPostCountRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	SearchMediaByName(ctx context.Context, arg SearchMediaByNameParams) ([]Medium, error)
	SearchTaxonomiesByName(ctx context.Context, arg SearchTaxonomiesByNameParams) ([]Taxonomy, error)
	TransferMediaToUser(ctx context.Context, arg TransferMediaToUserParams) error
	TransferPostsToAdmin(ctx context.Context, arg TransferPostsToAdminParams) error
	UpdateMedia(ctx context.Context, arg UpdateMediaParams) (Medium, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdatePostsUsername(ctx context.Context, arg UpdatePostsUsernameParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateSessionsUsername(ctx context.Context, arg UpdateSessionsUsernameParams) ([]Session, error)
	UpdateTaxonomy(ctx context.Context, arg UpdateTaxonomyParams) (Taxonomy, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPostsOwnership(ctx context.Context, arg UpdateUserPostsOwnershipParams) error
}

var _ Querier = (*Queries)(nil)
