// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreatePostTaxonomy(ctx context.Context, arg CreatePostTaxonomyParams) (PostsTaxonomy, error)
	CreatePosts(ctx context.Context, arg CreatePostsParams) (Post, error)
	CreateTaxonomy(ctx context.Context, arg CreateTaxonomyParams) (Taxonomy, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserPost(ctx context.Context, arg CreateUserPostParams) (UserPost, error)
	DeletePost(ctx context.Context, id int64) error
	DeletePostTaxonomies(ctx context.Context, postID int64) error
	DeletePostTaxonomy(ctx context.Context, arg DeletePostTaxonomyParams) error
	DeletePostsByUserID(ctx context.Context, userID int64) error
	DeleteTaxonomy(ctx context.Context, id int64) error
	DeleteTaxonomyPosts(ctx context.Context, taxonomyID int64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserPost(ctx context.Context, postID int64) error
	DeleteUserPostsByUserID(ctx context.Context, userID int64) error
	DeleteUserSessions(ctx context.Context, id int64) error
	GetPopularTaxonomies(ctx context.Context, limit int32) ([]GetPopularTaxonomiesRow, error)
	GetPost(ctx context.Context, id int64) (Post, error)
	GetPostTaxonomies(ctx context.Context, postID int64) ([]Taxonomy, error)
	GetPostTaxonomyCount(ctx context.Context, postID int64) (int64, error)
	GetTaxonomy(ctx context.Context, id int64) (Taxonomy, error)
	GetTaxonomyByName(ctx context.Context, name string) (Taxonomy, error)
	GetTaxonomyPostCount(ctx context.Context, taxonomyID int64) (int64, error)
	GetTaxonomyPosts(ctx context.Context, arg GetTaxonomyPostsParams) ([]Post, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error)
	ListTaxonomies(ctx context.Context, arg ListTaxonomiesParams) ([]Taxonomy, error)
	ListTaxonomiesWithPostCount(ctx context.Context, arg ListTaxonomiesWithPostCountParams) ([]ListTaxonomiesWithPostCountRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	SearchTaxonomiesByName(ctx context.Context, arg SearchTaxonomiesByNameParams) ([]Taxonomy, error)
	TransferPostsToAdmin(ctx context.Context, arg TransferPostsToAdminParams) error
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdatePostsUsername(ctx context.Context, arg UpdatePostsUsernameParams) error
	UpdateTaxonomy(ctx context.Context, arg UpdateTaxonomyParams) (Taxonomy, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPostsOwnership(ctx context.Context, arg UpdateUserPostsOwnershipParams) error
}

var _ Querier = (*Queries)(nil)
