// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreatePosts(ctx context.Context, arg CreatePostsParams) (Post, error)
}

var _ Querier = (*Queries)(nil)
