FROM node:22-alpine
WORKDIR /app

ARG PUBLIC_API_URL
ARG SERVER_API_URL

ENV PUBLIC_API_URL=$PUBLIC_API_URL
ENV SERVER_API_URL=$SERVER_API_URL

COPY package*.json ./
RUN npm install

EXPOSE 4321

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "4321"]